# Generated by Django 5.0.3 on 2024-03-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_manadatory_ds',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='is_manadatory_ie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='is_manadatory_se',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='lecture_hours',
            field=models.CharField(choices=[('M', 'Morning'), ('N', 'Noon'), ('E', 'Evening')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='course',
            name='pre_required_courses',
            field=models.ManyToManyField(blank=True, to='users.course'),
        ),
    ]
