# Generated by Django 5.0.3 on 2024-03-30 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_course_is_manadatory_ds_course_is_manadatory_ie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='future_text',
        ),
    ]
