# Generated by Django 5.0.3 on 2024-03-31 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userprofile_future_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningProgramCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_test',
        ),
        migrations.RemoveField(
            model_name='course',
            name='pre_required_courses',
        ),
        migrations.RemoveField(
            model_name='userrecommendation',
            name='recommended_courses',
        ),
        migrations.AddField(
            model_name='course',
            name='course_informetion',
            field=models.CharField(default='No information available', max_length=600),
        ),
        migrations.AddField(
            model_name='userrecommendation',
            name='explanation',
            field=models.TextField(default='No explanation available'),
        ),
        migrations.AddField(
            model_name='userrecommendation',
            name='predicted_rank',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userrecommendation',
            name='recommended_course',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='learning_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.learningprogramcourse'),
        ),
    ]
