# Generated by Django 5.0.3 on 2024-04-01 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_learningprogramcourse_remove_course_is_test_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='learning_program',
        ),
    ]
