# Generated by Django 5.0.3 on 2024-04-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_course_learning_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_informetion',
            field=models.TextField(),
        ),
    ]
