# Generated by Django 5.0.3 on 2024-04-08 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_userprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='preference_text',
            field=models.TextField(blank=True, help_text="I'm a [year of study] year student interested in [major or areas of interest]. I prefer [specific subjects, skills, or topics] over [other subjects or topics]. My best time for learning is [preferred learning time, e.g., morning, afternoon, evening] because that's when I feel most [describe how you feel, e.g., focused, energetic]. For me, it's more important to be really [interested/focus solely on grades], and I [prefer working on projects/prefer taking exams] as a way to assess my understanding. I'm looking for courses that [describe what you want from your courses, e.g., challenge me, expand my knowledge, offer practical experience, include engaging projects, or prepare me for exams] as I plan out the rest of my academic\xa0journey.", null=True),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
